template: Hello, %s!
defaultName: Stranger

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  rootPath: /api/
  adminContextPath: /admin/
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: notvalid
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: example.keystore
      keyStorePassword: notvalid
      validateCerts: false
